### ISSUE TITLE
.txt files

### ISSUE THREAD

**Issue by MalikQasimAli** [Gittingthehubbing/eyetracking_classification#1]
Hi, can I have the sample .txt files, please?

**Comment by Gittingthehubbing** [comment]
Hi,

I'm afraid I can't share the original data but you can easily fake it.
The N1.txt,N2.txt... look like this:

380987	  711.1	  328.1	  897.0	...
380988	  712.9	  327.7	  898.0	...
380989	  714.7	  326.8	  901.0	...
380990	  716.6	  325.9	  903.0	...
380991	  717.2	  325.0	  905.0	...
380992	  717.7	  323.9	  908.0	...
380993	  718.1	  323.0	  909.0	...
380994	  718.8	  322.1	  910.0	...

And the Outcome file is just the classification result for each N file, so either 1 or 0.

Hope this helps

**Comment by MalikQasimAli** [comment]
ok thank you. Is there any way to contact you?
my twitter profile is: https://twitter.com/qa_qasimali

**Comment by Gittingthehubbing** [comment]
I can share my LinkedIn if you're on there. Would that work?

**Comment by MalikQasimAli** [comment]
yes please that would be great.

**Comment by Gittingthehubbing** [comment]
Sure, it's https://www.linkedin.com/in/thomas-mercier-0001

**Comment by MalikQasimAli** [comment]
can I ask one more thing, 

I have ET data from a 60 Hz remote eye tracker. 

              
recording_id     timestamp     tracking_status
7536               1047780806               0
7536          1047791909                0
7536          1047803012                0
7536          1047814116                0
7536          1047825219                0

I implemented IDT algo to find fixation points. The problem is with the duration threshold. If I give a duration threshold limit from 100 to 11000, it returns the same number of fixation points. e.g. 888 fixation points.

But when I give the following duration threshold then, it gives me the results:

Duration threshold     total fixations
12000 till 22000              455
23000 till   31000              98


why do I have to give it in thousands in order to see the significant change? because of the timestamp? the timestamp was registered as the system timestamp at the time of recording. The depression threshold is 1.5 in all cases.

**Comment by Gittingthehubbing** [comment]
Sorry can't help with that. I've not worked on fixation extraction before.

**Comment by MalikQasimAli** [comment]
ok thank you :)
